seed: 1
model: 'SPACE'
resume: false
resume_ckpt: ''
parallel: false
device_ids: [0, 1]
device: 'cuda:0'
logdir: '../output/logs'
checkpointdir: '../output/checkpoints'
evaldir: '../output/eval/'

dataset: 'TABLE'
dataset_roots:
  TABLE: '../data/TABLE'


# For engine.train
train:
  batch_size: 32 #12
  max_epochs: 1000
  max_steps: 30000
  print_every: 600
  create_image_every: 600
  save_every: 1000
  num_workers: 0 #4
  clip_norm: 1.0
  max_ckpt: 4
  eval_on: true
  eval_every: 1000
  solver:
    fg:
      optim: 'RMSprop'
      lr: 1e-5
    bg:
      optim: 'Adam'
      lr: 1e-3

# For engine.eval
eval:
  checkpoint: 'best'
  metric: ap_avg

arch:
  G: 8
  img_shape: (64, 64)
  fg_sigma: 0.2

  z_pres_start_step: 4000
  z_pres_end_step: 10000
  z_pres_start_value: 0.1
  z_pres_end_value: 0.01

  z_scale_mean_start_step: 10000
  z_scale_mean_end_step: 20000
  z_scale_mean_start_value: -1.0
  z_scale_mean_end_value: -2.0

  tau_start_step: 0
  tau_end_step: 20000
  tau_start_value: 2.5
  tau_end_value: 0.5

  fix_alpha_steps: 0
  fix_alpha_value: 0.1

  K: 1
  bg_sigma: 0.05

  boundary_loss: true
  bl_off_step: 18000

